### ISSUE TITLE
import library

### ISSUE THREAD

**Issue by bonorico** [PonyGE/PonyGE2#109]
Dear all,
in my grammar there is an operation (cv2.add()) depending on cv2 library, which is not a PonyGE2 requirement. As a result, running my example returns "NameError: name 'cv2' is not defined". 
Where can I instruct to  import cv2 as a basic requirement, such that all operations in my grammar are defined ?
I hope I was clear in my explanation.

Thanks for any support

**Comment by jmmcd** [comment]
I think you just need to write "import cv2" at the top of your grammar. (I'm assuming your fitness function is calling exec(p), not eval(p), on the phenotype string p -- can you confirm?) 

I think this will *not* re-import cv2 on every fitness function call, so will not be slow. If it seems very slow there are some tricks that could be tried instead.

James

**Comment by bonorico** [comment]
Dear James, 
many thanks for your answer. I'm using a fitness function provided by PonyGE2, so I guess it is exec().
This is the grammar (just a minor edit of Vladislaveva4, including the cv2 operation)

<e>  ::=  <e>+<e>|
          <e>-<e>|
          <e>*<e>|
          pdiv(<e>,<e>)|
          psqrt(<e>)|
          np.sin(<e>)|
          np.tanh(<e>)|
          np.exp(<e>)|
          plog(<e>)|
	  cv2.add(<e>)|
          x[0]|x[1]|x[2]|x[3]|x[4]|
          <c><c>.<c><c>
<c>  ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9


where would you insert "import cv2" ?
Bestregards

**Comment by jmmcd** [comment]
Ah, I see. 

No, that uses `eval`: https://github.com/PonyGE/PonyGE2/blob/06b1a8cafb90196af8507b50c380fdf978bb68fa/src/fitness/supervised_learning/supervised_learning.py#L94

What happens when you write `import cv2` at the top of your fitness function `.py` file? I think this should work.

I don't know that `cv2.add()` will do anything different from `+`, but I guess maybe you are planning some other operations when the import is working correctly.

**Comment by bonorico** [comment]
Dear James,
thank you. putting 'import cv2' at the top of fitness/.supervised_learning/supervised_learning.py seems to correctly load cv2.
