### ISSUE TITLE
Additional stats

### ISSUE THREAD

**Issue by roestabiten** [PonyGE/PonyGE2#91]
I'd like to retrieve more stats from the fitness function, rather than only the fitness.

In this case I want the fitness function to return these stats and every individual to have these stats as attributes. This to later print it in stats.tsv for further analysis.  

Is this possible with the current functionality? I've gone through the wiki without having found anything about it.
If not, what would be the most efficient way to implement this in the code?

Thanks in advance.

**Comment by mikefenton** [comment]
Hi,

This is an interesting suggestion, but I'm not sure if it's something we would need to incorporate into the wider release; I think you can quite easily make some small modifications to your own version of PonyGE2 to achieve the desired functionality.

As each individual is an instance of a class, it makes sense to add a new attribute for each individual (such as `ind.stats`). You don't even need to modify the individual class itself, you can dynamically add this new attribute in your fitness function. Since the fitness function evaluates each individual in turn, you can simply define `ind.stats = [WHATEVER]` in your fitness function, with no need to return any additional stats values from the fitness function itself.

As for printing out these stats at a later stage, you will need to modify the main stats file to account for your new attributes. `stats.stats.update_stats()` is probably the one to look at, as it is where the main stats for printing are defined by the population. You can add a new entry to the main `stats.stats.stats` dictionary and update it in the `stats.stats.update_stats()` function when you look at the individuals themselves. Make sure to use a check for the presence of your new attribute if you're iterating over all individuals (e.g. `stats['new entry'] = x if hasattr(ind, 'stats') else np.NaN` or something like that) as if you're not modifying the base individual representation class then some individuals (e.g. invalids) may not have the required attribute if they cannot be evaluated.

Alternatively, you can simply do everything you wish for directly from the fitness function. If all you're doing is printing stuff to screen for later analysis, you can just print your desired stats directly from the fitness function and achieve the exact same end goal. You could even write these stats to a dedicated file. This would save all the hassle of having to add attributes and then having to modify the existing stats functions.

Hope that helps!

**Comment by roestabiten** [comment]
This will help a lot. Many thanks for the quick and exhaustive answer!
